# Generated by Django 3.0.5 on 2020-04-15 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"artist"',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"genre"',
                'ordering': ['genre_name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=250)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path', models.CharField(max_length=300, unique=True)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('bit_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Genre')),
            ],
            options={
                'db_table': '"song"',
                'ordering': ['song_name'],
            },
        ),
    ]
