# Generated by Django 3.0.5 on 2020-04-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
	('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=300, unique=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('set_date', models.DateField(db_index=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"playlist"',
                'ordering': ['set_date'],
            },
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
