# Generated by Django 3.0.5 on 2020-04-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200426_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='live_ind',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlist',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
