# Generated by Django 3.0.5 on 2020-04-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200426_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='set_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
