# Generated by Django 3.0.5 on 2020-04-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200428_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
