# Generated by Django 3.0.5 on 2020-04-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_delete_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=300, unique=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('set_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('live_ind', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"playlist"',
                'ordering': ['set_date'],
            },
        ),
    ]
