# Generated by Django 3.0.5 on 2020-05-04 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('show_date', models.DateField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.Playlist')),
            ],
            options={
                'db_table': '"show"',
                'ordering': ['show_date'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=300, unique=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
                ('shows', models.ManyToManyField(to='music.Show')),
            ],
            options={
                'db_table': '"video"',
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=300, unique=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
                ('shows', models.ManyToManyField(to='music.Show')),
            ],
            options={
                'db_table': '"image"',
                'ordering': ['created_date'],
            },
        ),
    ]
