# Generated by Django 3.0.5 on 2021-05-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200504_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='YTMSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=200, unique=True)),
                ('entityId', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('artist_name', models.CharField(max_length=250)),
                ('artist_id', models.CharField(blank=True, max_length=250, null=True)),
                ('album_name', models.CharField(blank=True, max_length=250, null=True)),
                ('album_id', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('last_updated_by', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"ytm_song"',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-show_date']},
        ),
    ]
