# Generated by Django 3.0.5 on 2021-05-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210502_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ytmsong',
            old_name='entityId',
            new_name='entity_id',
        ),
        migrations.RenameField(
            model_name='ytmsong',
            old_name='videoId',
            new_name='video_id',
        ),
    ]
