# Generated by Django 3.0.5 on 2021-05-08 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20210502_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='ytm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='music.YTMSong'),
        ),
    ]
